CREATE TABLE users
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tg_id      NUMBER(20),
    first_name VARCHAR2(500),
    last_name  VARCHAR2(500),
    username   VARCHAR2(500),
    lang_code  VARCHAR2(100),
    is_bot     VARCHAR2(1),
    created    TIMESTAMP WITH TIME ZONE,
    primary key (id)
);

